### ISSUE TITLE
error while running the script

### ISSUE THREAD

**Issue by saketvikram** [EikeDehling/spark-log-analysis#1]
bin/python ./top-urls.py
2018-07-06 14:07:24 WARN  Utils:66 - Your hostname, netops-Precision-M4800 resolves to a loopback address: 127.0.1.1; using 172.16.0.153 instead (on interface wlp3s0)
2018-07-06 14:07:24 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
2018-07-06 14:07:25 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2018-07-06 14:07:25 ERROR SparkUncaughtExceptionHandler:91 - Uncaught exception in thread Thread[main,5,main]
java.util.NoSuchElementException: key not found: _PYSPARK_DRIVER_CALLBACK_HOST
	at scala.collection.MapLike$class.default(MapLike.scala:228)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike$class.apply(MapLike.scala:141)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at org.apache.spark.api.python.PythonGatewayServer$$anonfun$main$1.apply$mcV$sp(PythonGatewayServer.scala:50)
	at org.apache.spark.util.Utils$.tryOrExit(Utils.scala:1302)
	at org.apache.spark.api.python.PythonGatewayServer$.main(PythonGatewayServer.scala:37)
	at org.apache.spark.api.python.PythonGatewayServer.main(PythonGatewayServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:879)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:197)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:227)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Traceback (most recent call last):
  File "./top-urls.py", line 5, in <module>
    sc = SparkContext('local[*]', 'Top Urls')
  File "/home/saket/Documents/sparkproj/spark-log-analysis/lib/python3.5/site-packages/pyspark/context.py", line 115, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/saket/Documents/sparkproj/spark-log-analysis/lib/python3.5/site-packages/pyspark/context.py", line 292, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/saket/Documents/sparkproj/spark-log-analysis/lib/python3.5/site-packages/pyspark/java_gateway.py", line 93, in launch_gateway
    raise Exception("Java gateway process exited before sending its port number")
Exception: Java gateway process exited before sending its port number

**Comment by EikeDehling** [comment]
Hi saktevitam,

your issue is related to network configration on your machine i believe.

See here:https://github.com/jaceklaskowski/mastering-apache-spark-book/blob/master/spark-tips-and-tricks.adoc#resolving-local-host-name

I would suggest trying the suggested solution of setting SPARK_LOCAL_HOSTNAME or SPARK_LOCAL_IP

Let me know if that helps

Eike
